<LS_Tab1>
    Button:
        id: add_button
        size_hint: (None, None)
        size: (130, 30)
        text: 'Connect to Chat'
        pos_hint: {'x': 0.01, 'y': 0.08}
        on_press:
            root.connect()
    Label:
        id: welcome_label
        text: ""
        height: dp(300)
        bold: True
        font_size: 50
        size: dp(600), dp(40)
        pos_hint: {'center_y': .85}